### ISSUE TITLE
Not able to build console/fatfs/spi example

### ISSUE THREAD

**Issue by deadprogram** [tinygo-org/tinyfs#4]
I was just trying to run the following, and ran into a build problem:

```
$ tinygo flash -target pyportal ./examples/console/fatfs/spi/                                                          
# github.com/tinygo-org/tinyfs/fatfs                                                                                   
fatfs/go_fatfs.go:163:11: ModeDir not declared by package os
```

@sago35 do you know anything to get around this?

**Comment by sago35** [comment]
You can use go1.15 to build it.
It seems to need some modification to make it work with go1.16. I'll take a look at it later.
@deadprogram

**Comment by deadprogram** [comment]
Thanks @sago35

**Comment by sago35** [comment]
The following changes will make it possible to build on go 1.16.
https://github.com/tinygo-org/tinygo/pull/1903

**Comment by deadprogram** [comment]
This was addressed some time ago. Closing, and will enter new issues as needed.
