### ISSUE TITLE
Change import path to tinygo.org/x/tinyfs

### ISSUE THREAD

**Issue by bgould** [tinygo-org/tinyfs#7]
The sdcard example from the drivers repository references tinyfs using the import path `github.com/tinygo-org/tinyfs` - https://github.com/tinygo-org/drivers/blob/24dfd8795aba54ae489b140cd7e467db8233e0d9/examples/sdcard/tinyfs/main.go#L8 - since that example has not made it into a release yet, it might be a good time to make the naming of the import consistent.

I propose that prior to the next release of the drivers`, the import path of this repository should be updated to be `tinygo.org/x/tinyfs`, and an initial release tag should be created and referenced from the drivers repository.  I'm not sure what needs to be done in order to make that import path work, I assume there is some edit to the tinygo.org site that may be necessary.

@deadprogram what is your opinion about this?

**Comment by deadprogram** [comment]
Sounds like a good plan to me.

**Comment by deadprogram** [comment]
Done here https://github.com/tinygo-org/tinygo-site/commit/bd0328de91539d3887379d2ca0cfdf179078c91c and will be deployed on next release.

**Comment by sago35** [comment]
I believe the following steps need to be taken.

1. release tinygo-site
2. update tinygo-org/tinyfs
3. update tinygo-org/drivers/examples/sdcard/tinyfs

**Comment by deadprogram** [comment]
This was all done, so now closing.
